package az.pro.shopping.util;

/**
 * Created by TALEH on 17.06.2016.
 */




public class Query {
//    public static final String GETADMINSHOPPINGLIST="SELECT L.ID,L.NAME,L.SURNAME,L.EMAIL,L.LOGIN_DATE,L.TASK,L.ACTIVE FROM LOGIN_TABLE_PRIMARY L WHERE L.ACTIVE=1";
    public static final String GETADMINSHOPPINGLIST="{call C##BIGDATA.SELECTPACKAGE.SHOWCUSTOMERS(?)}";
//    public static final String GETADMINORDEREDLIST="SELECT L.ID,L.NAME,L.SURNAME,L.EMAIL,P.ADDRESS,P.ORDER_DATE,P.LAST_DATE_OF_DELIVERY,P.MOBILE,P.MOBILE2,R.ONE,R.TWO,R.THREE,R.FOUR,R.FIVE,R.SIX,R.SEVEN,R.ACTIVE FROM LOGIN_TABLE_PRIMARY L\n" +
//            "LEFT JOIN PRIMARY_TABLE P ON L.ID=P.PRIMARY_ID\n" +
//            "LEFT JOIN RECEIVED_ORDERS R ON L.ID=R.PRIMARY_ID WHERE L.ACTIVE=1 AND P.ACTIVE=1 AND R.ACTIVE=1";

//    LTP_ID,LTP__NAME,LTP_SURNAME,LTP_EMAIL,PT_ADDRESS,PT_ORDER_DATE,PT_LAST_DATE_OF_DELIVERY,PT_MOBILE,PT_MOBILE2,S_NAME,RC_ORDER_COUNT,RC_ACTIVE
//    public static final String GETADMINORDEREDLIST="{call C##BIGDATA.SELECTPACKAGE.SHOWORDEREDLIST(?)}";
    public static final String SHOWFULLORDEREDLIST="{call C##BIGDATA.SELECTPACKAGE.SHOWFULLORDEREDLISTS(?)}";
//    public static final String GETADMINPRODUCTLIST="SELECT P.ID,P.NAME,P.PICTURE,P.PRICE,P.BONUCE_VALUE,P.IMPORTED_DATE,P.ACTIVE FROM PRODUCTS_ON_SALE P WHERE P.ACTIVE=1";
    public static final String GETADMINPRODUCTLIST="{call C##BIGDATA.SELECTPACKAGE.SHOWPRODUCTS(?)}";
//    public static final String GETADMINBONUCELIST="SELECT B.PRIMARY_ID,L.NAME,L.SURNAME,L.EMAIL,B.BONUCE_NAME,B.BONUCE_QUONTITY,B.OPEN_BONUCE_DATE,B.ACTIVE FROM LOGIN_TABLE_PRIMARY L\n"+
//            "LEFT JOIN BONUS_TABLE B ON L.ID=B.PRIMARY_ID WHERE L.ACTIVE=1 AND B.ACTIVE=1";
    public static final String GETADMINBONUCELIST="{call C##BIGDATA.SELECTPACKAGE.BONUCELIST(?)}";

//    public static final String EDITCUSTOMERLIST="SELECT L.ID,L.NAME,L.SURNAME,L.EMAIL,L.LOGIN_DATE,L.TASK,L.ACTIVE FROM LOGIN_TABLE_PRIMARY L WHERE  L.ID=?";
    public static final String EDITCUSTOMERLIST="{ ? = call C##BIGDATA.EDITPACKAGE.EDITCUSTOMERLIST(?)}";
//    public static final String EDITPRODUCTLIST="SELECT P.ID,P.NAME,P.PICTURE,P.PRICE,P.BONUCE_VALUE,P.IMPORTED_DATE,P.ACTIVE FROM PRODUCTS_ON_SALE P WHERE P.ID=?";
    public static final String EDITPRODUCTLIST="{? = call C##BIGDATA.EDITPACKAGE.EDITPRODUCTLIST(?)}";
//    public static final String EDITBONUCELIST="SELECT B.PRIMARY_ID,B.BONUCE_NAME,B.BONUCE_QUONTITY,B.OPEN_BONUCE_DATE,B.ACTIVE FROM BONUS_TABLE B WHERE B.PRIMARY_ID=?";
public static final String EDITBONUCELIST="{?=call C##BIGDATA.EDITPACKAGE.EDITBONUCELIST(?)}";




//    public static final String UPDATEBONUCELIST="UPDATE LOGIN_TABLE_PRIMARY SET LOGIN_DATE=?,TASK=?,ACTIVE=? WHERE ID=?";
    public static final String UPDATEBONUCELIST="{call C##BIGDATA.UPDATEPACKAGE.UPDATEBONUCELIST(?,?,?,?)}";
//    public static final String UPDATEPRODUCTLIST="UPDATE PRODUCTS_ON_SALE SET NAME=?,PRICE=?,BONUCE_VALUE=?,IMPORTED_DATE=?,ACTIVE=? WHERE ID=?";
    public static final String UPDATEPRODUCTLIST="{call C##BIGDATA.UPDATEPACKAGE.UPDATEPRODUCTLIST (?,?,?,?,?,?,?)}";
//    public static final String UPDATEPRODUCTPICTURELIST="UPDATE PRODUCTS_ON_SALE SET PICTURE=? WHERE ID=?";
    public static final String UPDATEPRODUCTPICTURELIST="{call C##BIGDATA.UPDATEPACKAGE.UPDATEPRODUCTPICTURELIST(?,?)}";
//    public static final String UPDATEBONUCENAMELIST="UPDATE BONUS_TABLE SET BONUCE_NAME=?,BONUCE_QUONTITY=?,OPEN_BONUCE_DATE=?,ACTIVE=? WHERE PRIMARY_ID=?";
    public static final String UPDATEBONUCENAMELIST="{call C##BIGDATA.UPDATEPACKAGE.UPDATEBONUCENAMELIST(?,?,?,?,?)}";
//    public static final String UPDATEPRODUCTACTIVE="UPDATE RECEIVED_ORDERS SET ACTIVE=? WHERE PRIMARY_ID=?";
    public static final String UPDATEPRODUCTACTIVE="{call C##BIGDATA.UPDATEPACKAGE.UPDATECUSTOMERACTIVE (?,?)}";

//    public static final String INSERTPRODUCTLIST="INSERT INTO PRODUCTS_ON_SALE (NAME,PICTURE,PRICE,BONUCE_VALUE) VALUES (?,?,?,?)";
//    public static final String INSERTPRICTURENAME="INSERT INTO PRODUCT_PICTURE (PRODUCT_ID,PRODUCT_PATH) VALUES (?,?)";
    public static final String INSERTPRODUCTANDPICTURENAE="{call C##BIGDATA.INSERTPACKAGE.INSERTPRODUCTLIST(?,?,?,?,?,?)}";


//    public static final String SENDCUSTOMERMAIL="SELECT EMAIL FROM LOGIN_TABLE_PRIMARY WHERE ID=?";
    public static final String SENDCUSTOMERMAIL="{?=call C##BIGDATA.SELECTPACKAGE.SENDCUSTOMERMAIL(?)}";
//    public static final String SENDALLCUSTOMERMAIL="SELECT ID,EMAIL FROM LOGIN_TABLE_PRIMARY WHERE ACTIVE=1 AND EMAIL_ACTIVE=1";
    public static final String SENDALLCUSTOMERMAIL="{call C##BIGDATA.SELECTPACKAGE.SENDALLCUSTOMERMAIL(?)}";

//    public static final String UPDATEEMAILACTIVE="UPDATE LOGIN_TABLE_PRIMARY SET EMAIL_ACTIVE=0 WHERE ID=?";
    public static final String UPDATEEMAILACTIVE="UPDATE LOGIN_TABLE_PRIMARY SET EMAIL_ACTIVE=0 WHERE ID=?";

//    public static final String SENDOLDCUSTOMERMAIL="SELECT ID,EMAIL FROM LOGIN_TABLE_PRIMARY WHERE ACTIVE=1 AND OLD_USER_ACTIVE=1";
    public static final String SENDOLDCUSTOMERMAIL="{call C##BIGDATA.SELECTPACKAGE.SENDOLDCUSTOMERMAIL(?)}";
//    public static final String SENDOLDTWOMONTHCUSTOMERMAIL="SELECT ID,EMAIL FROM LOGIN_TABLE_PRIMARY WHERE ACTIVE=1 AND OLD_USER_ACTIVE=0";
    public static final String SENDOLDTWOMONTHCUSTOMERMAIL="{call C##BIGDATA.SELECTPACKAGE.SENDOLDTWOMONTHCUSTOMERMAIL(?)}";
//    public static final String UPDATEOLDEMAILACTIVE="UPDATE LOGIN_TABLE_PRIMARY SET OLD_USER_ACTIVE=0 WHERE ID=?";
    public static final String UPDATEOLDEMAILACTIVE="{call C##BIGDATA.UPDATEPACKAGE.UPDATEOLDEMAILACTIVE(?)}";
//    public static final String UPDATEOLDTWOMONTHEMAILACTIVE="UPDATE LOGIN_TABLE_PRIMARY SET OLD_USER_ACTIVE=1 WHERE ID=?";
    public static final String UPDATEOLDTWOMONTHEMAILACTIVE="{call C##BIGDATA.UPDATEPACKAGE.UPDATEOLDTWOMONTHEMAILACTIVE(?)}";



    public static final String ADVSEARCHCUSTOMER="{?=call C##BIGDATA.ADVSEARCHPACKAGE.CUSTOMERADVSEARCH(?,?,?,?,?,?,?)}";
    public static final String ADVSEARCHORDEREDLIST="{?=call C##BIGDATA.ADVSEARCHPACKAGE.ORDEREDADVSEARCH(?,?,?,?,?,?,?,?,?,?,?,?,?,?)}";
    public static final String ADVSEARCHPRODUCTLIST="{?=call C##BIGDATA.ADVSEARCHPACKAGE.PRODUCTADV(?,?,?,?,?,?,?,?)}";

    public static final String CUSTOMERSGROUPBY="{call C##BIGDATA.SELECTPACKAGE.CUSTOMERSORDERBY(?)}";
    public static final String ORDEREDSGROUPBY="{call C##BIGDATA.SELECTPACKAGE.SHOWORDEREDORDERBYLIST(?)}";
    public static final String PRODUCTGROUPBY="{call C##BIGDATA.SELECTPACKAGE.SHOWPRODUCTSORDERBY(?)}";
    public static final String BONUCESGROUPBY="{call C##BIGDATA.SELECTPACKAGE.BONUCELISTORDERBY(?)}";
    public static final String ORDEREDDELIVERYDATESGROUPBY="{call C##BIGDATA.SELECTPACKAGE.ORDEREDDELIVERYDATEORDERBYLIST(?)}";

    public static final String INSERTCHECKBOX="{call C##BIGDATA.COMBOPACKAGE.INSERTPRODUCTCOMBO(?)}";
    public static final String PRODUCTANDCATEGORY="{call C##BIGDATA.SELECTUSER.PRODUCTANDCATEGORY(?)}";
    public static final String chartAction="{call C##BIGDATA.SELECTPACKAGE.CHARTSHOW(?)}";
    public static final String chartName="{call C##BIGDATA.SELECTPACKAGE.CHARTNAME(?)}";
}
